added links & ref port
Marat-Gumerov-Dev/TaskManager pull request #12
Opened 2022-10-12 19:43 UTC by Marat-Gumerov-Dev

added links & ref port

2022-10-12 19:45 UTC, greybutton requested changes

2022-10-12 19:45 UTC, greybutton commented on app/views/layouts/application.html.slim
> +    nav.mdl-navigation
уже есть такой элемент, в него надо добавить

2022-10-12 19:45 UTC, greybutton commented on config/puma.rb
> +set_default_host '0.0.0.0'
это откуда взял?

2022-10-12 19:45 UTC, greybutton commented on config/puma.rb
> +port ENV.fetch("PORT") { 8080 }
оставь как есть

2022-10-12 21:02 UTC, Marat-Gumerov-Dev commented on config/puma.rb
> +set_default_host '0.0.0.0'
прочитал в интернете.  а то нет доступа из контейнера

2022-10-12 21:02 UTC, Marat-Gumerov-Dev commented on config/puma.rb
> +port ENV.fetch("PORT") { 8080 }
дак а как я тогда зайду на порт 8080 ?

2022-10-13 06:05 UTC, greybutton commented on config/puma.rb
> +port ENV.fetch("PORT") { 8080 }
заходи по порту 3000

2022-10-13 06:05 UTC, greybutton approved these changes

2022-10-13 09:00 UTC, merged