Feature/generation controllers
Marat-Gumerov-Dev/TaskManager pull request #8
Opened 2022-10-07 09:47 UTC by Marat-Gumerov-Dev

created controller boards and sessions

2022-10-09 19:27 UTC, greybutton requested changes

2022-10-09 19:27 UTC, greybutton commented on config/application.rb
> +config.assets.paths << Rails.root.join('node_modules')
это нужно добавлять в class Application. На уровне файла нет config

2022-10-09 19:27 UTC, greybutton commented on config/initializers/simple_form_materialize.rb
> +  end
кажется отступы лишние

2022-10-09 19:52 UTC, Marat-Gumerov-Dev commented on config/initializers/simple_form_materialize.rb
> +  end
поправил. спасибо!

2022-10-10 07:58 UTC, greybutton approved these changes

2022-10-10 08:30 UTC, merged