added session and view
Marat-Gumerov-Dev/TaskManager pull request #9
Opened 2022-10-10 10:38 UTC by Marat-Gumerov-Dev

added session and view

2022-10-10 15:24 UTC, greybutton requested changes

2022-10-10 15:24 UTC, greybutton commented on config/routes.rb
> +    resource :session, only: [:new, :create, :destroy]
два ресурса сессии, нужна одна

2022-10-11 12:20 UTC, Marat-Gumerov-Dev commented on config/routes.rb
> +    resource :session, only: [:new, :create, :destroy]
Исправил спасибо!

2022-10-11 18:08 UTC, greybutton requested changes

2022-10-11 18:08 UTC, greybutton commented on err.txt
> +Run options: --seed 11607
странный файл попал, надо бы удалить

2022-10-11 20:26 UTC, Marat-Gumerov-Dev commented on err.txt
> +Run options: --seed 11607
Вы правы. удалил файл.

2022-10-12 06:58 UTC, greybutton approved these changes
не надо на гитхабе ставить в ревью, на нашей платформе мы увидим вашу отправку на ревью

2022-10-12 18:34 UTC, merged